name: Build Backend

on:
  push:
    branches:
      - main
    paths:
      - "backend/**"

jobs:
  build:
    name: Build backend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: "npm"
          cache-dependency-path: "**/package-lock.json"

      - name: Install
        run: npm ci

      - name: Compile
        run: npm run build

      - name: Setup git config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"

      - name: Commit
        run: |
          # Stage the file, commit and push
          git add build/*
          git commit -m "[CI] Compiled backend"
          git push origin main
